[package]
name = "iced-rs_app"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = "0.13.1"
iced_aw = "0.12.2"
serde_json = "1.0.140"
serde = { version = "1.0.219", features = ["derive"] }
rusqlite = "0.35.0"
sha2 = "0.10.9"
